snippet-add t "|tail -n10"
snippet-add h "|head -n10"
snippet-add g "|grep "
snippet-add l "|less "
snippet-add f "|fpp "
snippet-add y "|yank "
snippet-add Y "|yank -l "
snippet-add zp "${ZPREZD}/"
snippet-add zd "${ZPDOTD}/"
snippet-add tu "tulanthoar"
snippet-add nv "nvim "
snippet-add xm "xmonad"
snippet-add pw "${PWD}/"
snippet-add ex "unarchive "
snippet-add x "exit"
snippet-add q "exit"
snippet-add by "byobu-tmux "
snippet-add byn "byobu-tmux new-session "
snippet-add ns "new-session"
snippet-add byd "byobu-tmux detach"
snippet-add de "detach"
snippet-add add "git status | fpp"
snippet-add push "git commit && git push"
snippet-add mk "mkdir -p "
snippet-add df "df -h"
snippet-add st "startx"
snippet-add us "sudo dhcpcd $(ip link | grep -oE "\<enp[0-9]s[0-9]{2}[f0-9]?[u0-9]+\>")"
