snippet-add wi "sudo wifi-menu"
snippet-add t "|tail -n10"
snippet-add h "|head -n10"
snippet-add g "|grep "
snippet-add l "|less "
snippet-add f "|fpp "
snippet-add y "|yank "
snippet-add Y "|yank -l "
snippet-add zp "${ZPREZD}/"
snippet-add zd "${ZDOTD}/"
snippet-add v "nvim "
snippet-add tag "xmctl tagterm; byobu-tmux new-session"
snippet-add b "byobu-tmux "
snippet-add bn "byobu-tmux new-session"
snippet-add bd "byobu-tmux detach"
snippet-add add "git status | fpp"
snippet-add push "git commit && git push"
snippet-add mkd "mkdir -p "
snippet-add s "startx"
snippet-add p "pacman"
