snippet-add wi "sudo wifi-menu"
snippet-add t "|tail -n10"
snippet-add h "|head -n10"
snippet-add g "|grep "
snippet-add l "|less "
snippet-add f "|fpp "
snippet-add add "git status | fpp"
snippet-add push "git commit && git push"
snippet-add s "startx"
