#!/bin/sh
#
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

exec dbus-launch --exit-with-session xmonad
