#!/bin/bash
#
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        # shellcheck source=/etc/X11/xinit/xinitrc.d/50-systemd-user.sh
        # shellcheck source=/etc/X11/xinit/xinitrc.d/40-libcanberra-gtk-module.sh
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

export FREETYPE_PROPERTIES='truetype:interpreter-version=35'

read -r -d '' PyURxvtMeta8 <<-'EOF'
    #!/usr/bin/env python3

    import locale

    locale.setlocale(locale.LC_ALL, "")
    encoding = locale.getlocale()[1]

    # ASCII range
    for i in range(32, 128):
        seq = "".join("\{:o}".format(j) for j in chr(i + (1<<7)).encode(encoding))
        key = "{:#06X}".format(i)
        print("urxvt*keysym.Meta-{}: {}".format(key, seq))
EOF

xrdb -merge <(python3 <<<"$PyURxvtMeta8")

[[ -f "${HOME}"/.Xresources ]] && xrdb -merge -I"${HOME}" "${HOME}"/.Xresources
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# export LC_ALL=en_US.UTF-8

# exec startxfce4
#exec dbus-launch --exit-with-session xmonad
