#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export PERLDOC_SRC_PAGER='nvim'

export HISTFILE="${ZDOTDIR:-$HOME}/.zhistory"       # The path to the history file.
export HISTSIZE=10000                   # The maximum number of events to save in the internal history.
export SAVEHIST=10000                   # The maximum number of events to save in the history file.
[[ -z $LANG ]] && export LANG='en_US.UTF-8'

# Ensure path arrays do not contain duplicates.
typeset -gU fpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $path
  $HOME/bin
  $HOME/.local/bin
  $HOME/.gem/ruby/2.3.0/bin
  ${HOME}/.fzf/bin
)

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
(( $#commands[(i)lesspipe(|.sh)] )) && export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"

#
# Temporary Files
#

export TMPDIR=/tmp/$LOGNAME
[[ -d $TMPDIR ]]|| mkdir -p -m 700 $TMPDIR
export NVIM_LISTEN_ADDRESS=$TMPDIR/nvim_omni

TMPPREFIX=${TMPDIR%/}/zsh

export FZF_DEFAULT_OPTS='--reverse -i --cycle --select-1 --exit-0 --inline-info --color=fg:102,bg:233,hl:65,fg+:15,bg+:234,hl+:108,info:108,prompt:109,spinner:108,pointer:168,marker:168'
export FZF_TMUX_HEIGHT='80%'
export FZF_COMPLETION_TRIGGER=','
export FZF_COMPLETION_OPTS='+c -x'
which pt &> /dev/null && export FZF_DEFAULT_COMMAND='pt --hidden --ignore .git -g ""'
which ag &> /dev/null && export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
export KEYTIMEOUT=3
export LD_LIBRARY_PATH=${HOME}/.local/lib
export ZPREZD=${HOME}/.zprezto
export ZDOTD=${ZPREZD}/dotfiles
export ZBIND=${ZPREZD}/bin
export ZRCD=${ZPREZD}/runcoms
export GITAPPSD=${HOME}/apps-git
export FZFD=${HOME}/.fzf
# export JAVA_HOME="/usr/lib/jvm/default-jvm"
export GOPATH=$HOME/golang
[[ -d ${GOPATH} ]] && export PATH="$PATH:$GOPATH/bin"
export OMNIVIM_EDITOR=$(which nvim)
export BYOBU_WINDOWS=me
export PERL_UNICODE=AS
export PERL5OPTS="-Mperl5i -MIO::All"
export RANGER_LOAD_DEFAULT_RC=FALSE
export JAVA_TOOL_OPTIONS="-Dgnu.io.rxtx.SerialPorts=/dev/tty96B0"
export MONITOR_PORT="/dev/tty96B0"
export BYOBU_CONFIG_DIR="${HOME}/.config/byobu"
