# vim: set ft=zsh:
# [[ -f ${HOME}/.terminfo/${TERM[1]}/${TERM} ]] || infocmp ${TERM} | sed 's/kbs=^[hH]/kbs=\\177/' | tic -
# function zshrcload(){
autoload -Uw /usr/share/zsh/functions/{Completion/Completion.zwc,Misc/Misc.zwc,Prompts/Prompt.zwc}
zmodload zsh/zutil
zmodload zsh/complist
zmodload zsh/deltochar
zstyle ':prezto:*:*' 'color' 'yes'
zstyle ':completion:*' 'menu' "select"
zstyle -e ':completion:*:default' 'list-colors' 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)*==34=16}:${(s.:.)LS_COLORS}")';
zstyle ':filter-select' 'case-insensitive' 'yes' # enable case-insensitive search
zstyle ':filter-select' 'extended-search' 'yes'
zstyle ':filter-select' 'hist-find-no-dups' 'yes' # ignore duplicates in history source
__options_env
__myaliases
promptinit
prompt "paradox"
add-zsh-hook preexec alias-tips-preexec
chpwd_functions+=(git-status l)
fpath+=(${ZPREZD}/modules/zsh-completions/src)
function (){
    local cmnd=pacman
    [[ ${${cmnd}:c} = ${cmnd} ]] || source ${ZPREZD}/modules/pacman/init.zsh
}
function (){
    local cmnd=tag
    if [[ ${${cmnd}:c} != ${cmnd} ]]; then
        function tag() {
            command tag "$@";
            eval $(perl -ne 's/''vim /''nvim /; print "$_";' < ${TAG_ALIAS_FILE})
        }
    fi
}
function (){
    local re_initialize=0
    if [[ -n ${ZDOTDIR:-${HOME}}/${ZSH_COMPDUMP:-.zcompdump}(#qN.mh+24) ]]; then
        re_initialize=1
    fi
    if [ "$re_initialize" -eq "1" ]; then
        compinit -d ${ZDOTDIR:-${HOME}}/${ZSH_COMPDUMP:-.zcompdump}
        compdump
    else
        compinit -d ${ZDOTDIR:-${HOME}}/${ZSH_COMPDUMP:-.zcompdump} -C
    fi
}
# fpath+=(${ZPREZD}/modules/zsh-abbrev-alias/src)
# autoload -Uw $ZPREZD/modules/zsh-abbrev-alias/src/abbrev-alias.zwc
# abbrev-alias --init

# fpath+=(${ZPREZD}/modules/zsh-manydots-magic)
# autoload -Uz manydots-magic
# }
# autoload -U zshrcload && zshrcload
# function zshintload(){
# [[ -s "$HOME/.local/share/marker/marker.sh" ]] && source "$HOME/.local/share/marker/marker.sh"
# source "$ZPREZD/modules/fzf/shell/completion.zsh"
source "${ZPREZD}/modules/fasd.zsh"
source "${ZPREZD}/modules/calc/calc.plugin.zsh"
# source "${ZPREZD}/modules/careful_rm/careful_rm.plugin.zsh"
source "${ZPREZD}/modules/zsh-autopair/autopair.zsh"
source "${ZPREZD}/modules/zsh-change-case/change-case.zsh"
source "${ZPREZD}/modules/zce/zce.zsh"
source "${ZPREZD}/modules/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh"
source "${ZPREZD}/modules/zaw/zaw.zsh"
source "${ZPREZD}/modules/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
zle_widgets
source "${ZPREZD}/modules/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
source "${ZPREZD}/modules/q/q.plugin.zsh"
source "${ZPREZD}/modules/history-substring-search/external/zsh-history-substring-search.zsh"
highlight_styles
key_bind
# }
# autoload -U zshrcload && zshrcload
# zprof
# autoload -U zshfinload && zshfinload
# zprof &>${HOME}/profiled
