#!/bin/bash

perl -pi -e 's/^#en_US\./en_US\./' /etc/locale.gen && \
perl -pi -e 's/^es_US\.UTF-8/#es_US\.UTF-8/' /etc/locale.gen
locale-gen
hostnamectl set-hostname arch
timedatectl set-timezone 'America/Denver'
perl -p -e </etc/sudoers "s/^## User privilege specification$/arch ALL=\\(ALL\\) NOPASSWD: ALL/" | tee mysudo | visudo -c -s -f- && cat mysudo > /etc/sudoers
mkdir -p /home/arch
touch /home/arch/.z{shenv,profile,shrc,login}
echo 'sudo pacman -Syu --noconfirm git>/dev/null' >> /home/arch/.zshrc
echo 'git clone --recursive https://github.com/tulanthoar/prezto /home/arch/.zprezto &> /dev/null' >> /home/arch/.zshrc
echo '/home/arch/.zprezto/strap.zsh' >> /home/arch/.zshrc
echo '"hello"' > /etc/motd
useradd -p 'arch11' -s /bin/zsh arch
echo 'arch:arch11'|chpasswd
chown arch:arch /home/arch
chown arch:arch /home/arch/.z{shenv,profile,shrc,login}
pacman -S --noconfirm zsh
