snippet-add t "|tail -n10"
snippet-add h "|head -n10"
snippet-add g "|grep "
snippet-add l "|less "
snippet-add f "|fpp "
snippet-add y "|yank "
snippet-add Y "|yank -l "
snippet-add zp "${ZPREZD}/"
snippet-add zd "${ZPDOTD}/"
snippet-add zr "${ZPRCD}/"
snippet-add tu "tulanthoar"
snippet-add v "nvim "
snippet-add . "${PWD}/"
snippet-add b "byobu-tmux "
snippet-add bn "byobu-tmux new-session "
snippet-add n "new-session"
snippet-add bd "byobu-tmux detach"
snippet-add d "detach"
snippet-add add "git status | fpp"
snippet-add push "git commit && git push"
snippet-add mk "mkdir -p "
snippet-add s "startx"
# snippet-add us "sudo dhcpcd $(ip link | grep -oE "\<enp[0-9]s[0-9]{2}[f0-9]?[u0-9]+\>")"
snippet-add p "pacman"
